from sqlalchemy import BigInteger, Column, DateTime, Integer, MetaData, Numeric, String, Table
from sqlalchemy.dialects.postgresql import JSONB, UUID

from creative_marketer.infrastructure.database.schema import NAMING_CONVENTION

metadata = MetaData(naming_convention=NAMING_CONVENTION)

agent_runs = Table(
    "agent_runs",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column("tenant_id", UUID(as_uuid=True), nullable=False),
    Column("requested_agent_definition_id", UUID(as_uuid=True), nullable=False),
    Column("resolved_agent_definition_id", UUID(as_uuid=True), nullable=False),
    Column("agent_version_id", UUID(as_uuid=True), nullable=False),
    Column("agent_version_number", Integer, nullable=False),
    Column("agent_configuration_digest", String(71), nullable=False),
    Column("prompt_revision", String(128), nullable=False),
    Column("product_id", UUID(as_uuid=True), nullable=False),
    Column("product_snapshot_id", UUID(as_uuid=True), nullable=False),
    Column("product_snapshot_digest", String(71), nullable=False),
    Column("product_snapshot_schema_version", Integer, nullable=False),
    Column("research_context_digest", String(71), nullable=False),
    Column("context_digest", String(71), nullable=False),
    Column("selected_evidence", JSONB, nullable=False),
    Column("model_profile_key", String(128), nullable=False),
    Column("output_contract_key", String(128), nullable=False),
    Column("output_contract_version", Integer, nullable=False),
    Column("correlation_id", UUID(as_uuid=True), nullable=False),
    Column("initiated_by_actor_kind", String(32), nullable=False),
    Column("initiated_by_actor_id", UUID(as_uuid=True), nullable=False),
    Column("period_start", DateTime(timezone=True), nullable=False),
    Column("reserved_cost", Numeric(19, 6), nullable=False),
    Column("currency", String(3), nullable=False),
    Column("idempotency_key", String(128), nullable=False),
    Column("recovery_of_run_id", UUID(as_uuid=True)),
    Column("status", String(32), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("started_at", DateTime(timezone=True)),
    Column("completed_at", DateTime(timezone=True)),
    Column("executed_by_workload_id", String(128)),
    Column("resolved_provider", String(64)),
    Column("resolved_model", String(128)),
    Column("resolved_model_route_version", String(64)),
    Column("pricing_version", String(64)),
    Column("reasoning_effort", String(32)),
    Column("max_output_tokens", Integer),
    Column("max_total_tokens", Integer, nullable=False),
    Column("model_call_count", Integer, nullable=False),
    Column("input_tokens", BigInteger, nullable=False),
    Column("output_tokens", BigInteger, nullable=False),
    Column("total_tokens", BigInteger, nullable=False),
    Column("estimated_cost", Numeric(19, 6), nullable=False),
    Column("provider_response_id", String(256)),
    Column("result_ref", String(256)),
    Column("failure_code", String(100)),
    schema="agent_runtime",
)

agent_budget_usage = Table(
    "agent_budget_usage",
    metadata,
    Column("tenant_id", UUID(as_uuid=True), primary_key=True),
    Column("agent_definition_id", UUID(as_uuid=True), primary_key=True),
    Column("period_start", DateTime(timezone=True), primary_key=True),
    Column("currency", String(3), nullable=False),
    Column("reserved_runs", Integer, nullable=False),
    Column("reserved_cost", Numeric(19, 6), nullable=False),
    Column("actual_cost", Numeric(19, 6), nullable=False),
    Column("unknown_cost", Numeric(19, 6), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    schema="agent_runtime",
)

model_attempts = Table(
    "model_attempts",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column("tenant_id", UUID(as_uuid=True), nullable=False),
    Column("agent_run_id", UUID(as_uuid=True), nullable=False),
    Column("attempt_number", Integer, nullable=False),
    Column("workload_id", String(128), nullable=False),
    Column("model_route_version", String(64), nullable=False),
    Column("pricing_version", String(64), nullable=False),
    Column("provider", String(64), nullable=False),
    Column("model", String(128), nullable=False),
    Column("status", String(32), nullable=False),
    Column("claimed_at", DateTime(timezone=True), nullable=False),
    Column("provider_started_at", DateTime(timezone=True)),
    Column("response_recorded_at", DateTime(timezone=True)),
    Column("finished_at", DateTime(timezone=True)),
    Column("lease_expires_at", DateTime(timezone=True), nullable=False),
    Column("provider_response_id", String(256)),
    Column("input_tokens", BigInteger, nullable=False),
    Column("output_tokens", BigInteger, nullable=False),
    Column("total_tokens", BigInteger, nullable=False),
    Column("estimated_cost", Numeric(19, 6), nullable=False),
    Column("unknown_cost", Numeric(19, 6), nullable=False),
    Column("failure_code", String(100)),
    schema="agent_runtime",
)

model_cost_reconciliations = Table(
    "model_cost_reconciliations",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column("tenant_id", UUID(as_uuid=True), nullable=False),
    Column("agent_run_id", UUID(as_uuid=True), nullable=False),
    Column("model_attempt_id", UUID(as_uuid=True), nullable=False),
    Column("unknown_cost", Numeric(19, 6), nullable=False),
    Column("actual_cost", Numeric(19, 6), nullable=False),
    Column("currency", String(3), nullable=False),
    Column("reconciled_by_workload_id", String(128), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    schema="agent_runtime",
)

research_snapshots = Table(
    "research_snapshots",
    metadata,
    Column("id", UUID(as_uuid=True), primary_key=True),
    Column("tenant_id", UUID(as_uuid=True), nullable=False),
    Column("product_id", UUID(as_uuid=True), nullable=False),
    Column("agent_run_id", UUID(as_uuid=True), nullable=False),
    Column("schema_version", Integer, nullable=False),
    Column("product_snapshot_id", UUID(as_uuid=True), nullable=False),
    Column("product_snapshot_digest", String(71), nullable=False),
    Column("research_context_digest", String(71), nullable=False),
    Column("findings", JSONB, nullable=False),
    Column("research_gaps", JSONB, nullable=False),
    Column("recommended_next_sources", JSONB, nullable=False),
    Column("semantic_digest", String(71), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("valid_until", DateTime(timezone=True), nullable=False),
    schema="research",
)
