/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness */
    get: operations["liveness_health_live_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness */
    get: operations["readiness_health_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/brands": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Brands */
    get: operations["list_brands_v1_brands_get"];
    put?: never;
    /** Create Brand */
    post: operations["create_brand_v1_brands_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/brands/{brand_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Brand */
    get: operations["get_brand_v1_brands__brand_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Brand */
    patch: operations["update_brand_v1_brands__brand_id__patch"];
    trace?: never;
  };
  "/v1/brands/{brand_id}/products": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Brand Products */
    get: operations["list_brand_products_v1_brands__brand_id__products_get"];
    put?: never;
    /** Create Product */
    post: operations["create_product_v1_brands__brand_id__products_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Current Actor */
    get: operations["get_current_actor_v1_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/products/{product_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Product */
    get: operations["get_product_v1_products__product_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Product */
    patch: operations["update_product_v1_products__product_id__patch"];
    trace?: never;
  };
  "/v1/products/{product_id}/brief": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Brief */
    get: operations["get_brief_v1_products__product_id__brief_get"];
    /** Put Brief */
    put: operations["put_brief_v1_products__product_id__brief_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/products/{product_id}/brief/completeness": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Completeness */
    get: operations["get_completeness_v1_products__product_id__brief_completeness_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/products/{product_id}/snapshots": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Snapshot */
    post: operations["create_snapshot_v1_products__product_id__snapshots_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/products/{product_id}/snapshots/latest": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Latest Snapshot */
    get: operations["latest_snapshot_v1_products__product_id__snapshots_latest_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tenants/{tenant_id}/context": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Tenant Context */
    get: operations["get_tenant_context_v1_tenants__tenant_id__context_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AudienceContract */
    AudienceContract: {
      /**
       * Description
       * @default
       */
      description: string;
      /** Desires */
      desires?: string[];
      /** Motivations */
      motivations?: string[];
      /** Name */
      name: string;
      /** Objections */
      objections?: string[];
      /** Pain Points */
      pain_points?: string[];
    };
    /** BrandProfileContract */
    BrandProfileContract: {
      /** Allowed Claims */
      allowed_claims?: string[];
      /**
       * Brand Positioning
       * @default
       */
      brand_positioning: string;
      /**
       * Brand Voice
       * @default
       */
      brand_voice: string;
      /** Competitors */
      competitors?: string[];
      /**
       * Description
       * @default
       */
      description: string;
      /**
       * Industry
       * @default
       */
      industry: string;
      /**
       * Primary Language
       * @default en
       */
      primary_language: string;
      /** Prohibited Claims */
      prohibited_claims?: string[];
      /** Target Markets */
      target_markets?: string[];
      /** Tone Attributes */
      tone_attributes?: string[];
      /** Visual Style Keywords */
      visual_style_keywords?: string[];
    };
    /** BrandResponse */
    BrandResponse: {
      /**
       * Can Edit
       * @default false
       */
      can_edit: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Created By
       * Format: uuid
       */
      created_by: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      profile?: components["schemas"]["BrandProfileContract"];
      /** Slug */
      slug: string;
      /**
       * Status
       * @default active
       * @enum {string}
       */
      status: "active" | "archived";
      /**
       * Tenant Id
       * Format: uuid
       */
      tenant_id: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Website Url */
      website_url?: string | null;
    };
    /** BrandWrite */
    BrandWrite: {
      /** Name */
      name: string;
      profile?: components["schemas"]["BrandProfileContract"];
      /** Slug */
      slug: string;
      /**
       * Status
       * @default active
       * @enum {string}
       */
      status: "active" | "archived";
      /** Website Url */
      website_url?: string | null;
    };
    /** BriefContract */
    BriefContract: {
      /** Competitive Alternatives */
      competitive_alternatives?: string[];
      /**
       * Conversion Goal
       * @default
       */
      conversion_goal: string;
      /** Creative References */
      creative_references?: string[];
      /** Cta Preferences */
      cta_preferences?: string[];
      /** Current Channels */
      current_channels?: string[];
      /**
       * Desired Creative Style
       * @default
       */
      desired_creative_style: string;
      /** Emotional Benefits */
      emotional_benefits?: string[];
      /** Geographical Restrictions */
      geographical_restrictions?: string[];
      /** Legal Safety Constraints */
      legal_safety_constraints?: string[];
      /** Mandatory Messaging */
      mandatory_messaging?: string[];
      /** Offers */
      offers?: string[];
      /**
       * Positioning Statement
       * @default
       */
      positioning_statement: string;
      primary_audience?: components["schemas"]["AudienceContract"] | null;
      /** Priority Channels */
      priority_channels?: string[];
      /**
       * Product Why
       * @default
       */
      product_why: string;
      /** Prohibited Messaging */
      prohibited_messaging?: string[];
      /** Required Disclaimers */
      required_disclaimers?: string[];
      /** Secondary Audiences */
      secondary_audiences?: components["schemas"]["AudienceContract"][];
      /** Tones To Avoid */
      tones_to_avoid?: string[];
      /** Tones To Explore */
      tones_to_explore?: string[];
      /** Why Choose Us */
      why_choose_us?: string[];
    };
    /** BriefResponse */
    BriefResponse: {
      /** Can Edit */
      can_edit: boolean;
      /** Competitive Alternatives */
      competitive_alternatives?: string[];
      /**
       * Conversion Goal
       * @default
       */
      conversion_goal: string;
      /** Creative References */
      creative_references?: string[];
      /** Cta Preferences */
      cta_preferences?: string[];
      /** Current Channels */
      current_channels?: string[];
      /**
       * Desired Creative Style
       * @default
       */
      desired_creative_style: string;
      /** Emotional Benefits */
      emotional_benefits?: string[];
      /** Geographical Restrictions */
      geographical_restrictions?: string[];
      /** Legal Safety Constraints */
      legal_safety_constraints?: string[];
      /** Mandatory Messaging */
      mandatory_messaging?: string[];
      /** Offers */
      offers?: string[];
      /**
       * Positioning Statement
       * @default
       */
      positioning_statement: string;
      primary_audience?: components["schemas"]["AudienceContract"] | null;
      /** Priority Channels */
      priority_channels?: string[];
      /**
       * Product Id
       * Format: uuid
       */
      product_id: string;
      /**
       * Product Why
       * @default
       */
      product_why: string;
      /** Prohibited Messaging */
      prohibited_messaging?: string[];
      /** Required Disclaimers */
      required_disclaimers?: string[];
      /** Revision */
      revision: number;
      /** Secondary Audiences */
      secondary_audiences?: components["schemas"]["AudienceContract"][];
      /** Tones To Avoid */
      tones_to_avoid?: string[];
      /** Tones To Explore */
      tones_to_explore?: string[];
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Why Choose Us */
      why_choose_us?: string[];
    };
    /** CompletenessResponse */
    CompletenessResponse: {
      /** Missing Fields */
      missing_fields: string[];
      /** Missing Sections */
      missing_sections: string[];
      /** Score */
      score: number;
    };
    /** CurrentActorResponse */
    CurrentActorResponse: {
      /** Actor Kind */
      actor_kind: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
    };
    /** ExecutionContextResponse */
    ExecutionContextResponse: {
      /** Actor Kind */
      actor_kind: string;
      /**
       * Correlation Id
       * Format: uuid
       */
      correlation_id: string;
      /** Membership Role */
      membership_role: string;
      /**
       * Tenant Id
       * Format: uuid
       */
      tenant_id: string;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** ProductCreate */
    ProductCreate: {
      brief?: components["schemas"]["BriefContract"];
      /** Category */
      category: string;
      /** Name */
      name: string;
      profile?: components["schemas"]["ProductProfileContract-Input"];
      /**
       * Short Description
       * @default
       */
      short_description: string;
      /** Sku */
      sku?: string | null;
      /** Slug */
      slug: string;
      /**
       * Status
       * @default draft
       * @enum {string}
       */
      status: "draft" | "active" | "archived";
    };
    /** ProductProfileContract */
    "ProductProfileContract-Input": {
      /** Allowed Claims */
      allowed_claims?: string[];
      /** Benefits */
      benefits?: string[];
      /** Competitor Product Refs */
      competitor_product_refs?: string[];
      /** Currency */
      currency?: string | null;
      /**
       * Description
       * @default
       */
      description: string;
      /** Differentiators */
      differentiators?: string[];
      /** Estimated Margin */
      estimated_margin?: number | string | null;
      /** Features */
      features?: string[];
      /** Landing Page Url */
      landing_page_url?: string | null;
      /** Materials */
      materials?: string[];
      /** Price */
      price?: number | string | null;
      /** Problems Solved */
      problems_solved?: string[];
      /** Prohibited Claims */
      prohibited_claims?: string[];
      /** Purchase Objections */
      purchase_objections?: string[];
      /** Seasonality Notes */
      seasonality_notes?: string | null;
      /** Shipping Summary */
      shipping_summary?: string | null;
      /** Target Audiences */
      target_audiences?: components["schemas"]["AudienceContract"][];
      /** Use Cases */
      use_cases?: string[];
      /** Variants */
      variants?: string[];
    };
    /** ProductProfileContract */
    "ProductProfileContract-Output": {
      /** Allowed Claims */
      allowed_claims?: string[];
      /** Benefits */
      benefits?: string[];
      /** Competitor Product Refs */
      competitor_product_refs?: string[];
      /** Currency */
      currency?: string | null;
      /**
       * Description
       * @default
       */
      description: string;
      /** Differentiators */
      differentiators?: string[];
      /** Estimated Margin */
      estimated_margin?: string | null;
      /** Features */
      features?: string[];
      /** Landing Page Url */
      landing_page_url?: string | null;
      /** Materials */
      materials?: string[];
      /** Price */
      price?: string | null;
      /** Problems Solved */
      problems_solved?: string[];
      /** Prohibited Claims */
      prohibited_claims?: string[];
      /** Purchase Objections */
      purchase_objections?: string[];
      /** Seasonality Notes */
      seasonality_notes?: string | null;
      /** Shipping Summary */
      shipping_summary?: string | null;
      /** Target Audiences */
      target_audiences?: components["schemas"]["AudienceContract"][];
      /** Use Cases */
      use_cases?: string[];
      /** Variants */
      variants?: string[];
    };
    /** ProductResponse */
    ProductResponse: {
      /**
       * Brand Id
       * Format: uuid
       */
      brand_id: string;
      /**
       * Can Edit
       * @default false
       */
      can_edit: boolean;
      /** Category */
      category: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Created By
       * Format: uuid
       */
      created_by: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      profile?: components["schemas"]["ProductProfileContract-Output"];
      /**
       * Short Description
       * @default
       */
      short_description: string;
      /** Sku */
      sku?: string | null;
      /** Slug */
      slug: string;
      /**
       * Status
       * @default draft
       * @enum {string}
       */
      status: "draft" | "active" | "archived";
      /**
       * Tenant Id
       * Format: uuid
       */
      tenant_id: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ProductWrite */
    ProductWrite: {
      /** Category */
      category: string;
      /** Name */
      name: string;
      profile?: components["schemas"]["ProductProfileContract-Input"];
      /**
       * Short Description
       * @default
       */
      short_description: string;
      /** Sku */
      sku?: string | null;
      /** Slug */
      slug: string;
      /**
       * Status
       * @default draft
       * @enum {string}
       */
      status: "draft" | "active" | "archived";
    };
    /** SnapshotResponse */
    SnapshotResponse: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Digest */
      digest: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Product Id
       * Format: uuid
       */
      product_id: string;
      /** Schema Version */
      schema_version: number;
      /** Source Revision */
      source_revision: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** WorkspaceResponse */
    WorkspaceResponse: {
      brand: components["schemas"]["BrandResponse"];
      brief: components["schemas"]["BriefResponse"];
      completeness: components["schemas"]["CompletenessResponse"];
      latest_snapshot: components["schemas"]["SnapshotResponse"] | null;
      product: components["schemas"]["ProductResponse"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  liveness_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  readiness_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  list_brands_v1_brands_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        "X-Tenant-ID"?: string | null;
        "X-Correlation-ID"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BrandResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_brand_v1_brands_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        "X-Tenant-ID"?: string | null;
        "X-Correlation-ID"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BrandWrite"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BrandResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_brand_v1_brands__brand_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        "X-Tenant-ID"?: string | null;
        "X-Correlation-ID"?: string | null;
      };
      path: {
        brand_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BrandResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_brand_v1_brands__brand_id__patch: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        "X-Tenant-ID"?: string | null;
        "X-Correlation-ID"?: string | null;
      };
      path: {
        brand_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BrandWrite"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BrandResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_brand_products_v1_brands__brand_id__products_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        "X-Tenant-ID"?: string | null;
        "X-Correlation-ID"?: string | null;
      };
      path: {
        brand_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_product_v1_brands__brand_id__products_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        "X-Tenant-ID"?: string | null;
        "X-Correlation-ID"?: string | null;
      };
      path: {
        brand_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_current_actor_v1_me_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentActorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_product_v1_products__product_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        "X-Tenant-ID"?: string | null;
        "X-Correlation-ID"?: string | null;
      };
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_product_v1_products__product_id__patch: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        "X-Tenant-ID"?: string | null;
        "X-Correlation-ID"?: string | null;
      };
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductWrite"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_brief_v1_products__product_id__brief_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        "X-Tenant-ID"?: string | null;
        "X-Correlation-ID"?: string | null;
      };
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BriefResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  put_brief_v1_products__product_id__brief_put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        "X-Tenant-ID"?: string | null;
        "X-Correlation-ID"?: string | null;
      };
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BriefContract"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BriefResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_completeness_v1_products__product_id__brief_completeness_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        "X-Tenant-ID"?: string | null;
        "X-Correlation-ID"?: string | null;
      };
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompletenessResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_snapshot_v1_products__product_id__snapshots_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        "X-Tenant-ID"?: string | null;
        "X-Correlation-ID"?: string | null;
      };
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SnapshotResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  latest_snapshot_v1_products__product_id__snapshots_latest_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        "X-Tenant-ID"?: string | null;
        "X-Correlation-ID"?: string | null;
      };
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SnapshotResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_tenant_context_v1_tenants__tenant_id__context_get: {
    parameters: {
      query?: never;
      header?: {
        "X-Correlation-ID"?: string | null;
        authorization?: string | null;
      };
      path: {
        tenant_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExecutionContextResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
